daysUntilStale: 360
daysUntilClose: 7
exemptLabels:
  - acknowledged
staleLabel: wontfix
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
  
  Also see https://github.com/mueller-ma/MuteReminder#maintenance-notice
closeComment: false
