name: Build App

on: [push, pull_request]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3.5.0

      - name: Build
        run: bash gradlew build

      - name: Upload unsigned APK
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-apk
          path: app/build/outputs/apk
